# Generated by Django 5.2.3 on 2025-07-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='Post',
            new_name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
